### ISSUE TITLE
README.md outdated

### ISSUE THREAD

**Issue by porst17** [Robobench/tacklebox#5]
I just stumbled upon your very interesting project. However, following the instructions in the README.md just results in

```
python: can't open file 'tackle.py': [Errno 2] No such file or directory
```

Looks like something has changed since the last update of the README.md.

I am new to python. Hence, it is not straightforward to track this issue down. It's obvious that `tackle.py` has been removed or renamed, but that's as far as I can get right now.

I also tried

```
sudo python setup.py install
```

and then

```
 tackle component-demo
```

but this results in 

```
Traceback (most recent call last):
  File "/usr/local/bin/tackle", line 4, in <module>
    __import__('pkg_resources').run_script('tacklebox==0.0.1', 'tackle')
  File "~/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "~/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/tacklebox-0.0.1-py2.7.egg/EGG-INFO/scripts/tackle", line 137, in <module>
    t = TackleBox(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/tacklebox-0.0.1-py2.7.egg/EGG-INFO/scripts/tackle", line 26, in __init__
    self._parse(inputs)
  File "/usr/local/lib/python2.7/dist-packages/tacklebox-0.0.1-py2.7.egg/tacklebox/tools/subcommand.py", line 86, in _parse
    self.subcommands[which](result_dict)
  File "/usr/local/lib/python2.7/dist-packages/tacklebox-0.0.1-py2.7.egg/tacklebox/tools/subcommand.py", line 18, in __call__
    self.__method(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tacklebox-0.0.1-py2.7.egg/EGG-INFO/scripts/tackle", line 118, in component_demo
    docker_runner = docker_subprocess.DockerRunPopen(image, interactive=True, dockerargs=self.__get_component_arguments(),rm=True)
  File "/usr/local/lib/python2.7/dist-packages/tacklebox-0.0.1-py2.7.egg/EGG-INFO/scripts/tackle", line 32, in __get_component_arguments
    argument_strings.extend(self.__get_arguments_from_dict(self.__generate_final_argument_dict()))
  File "/usr/local/lib/python2.7/dist-packages/tacklebox-0.0.1-py2.7.egg/EGG-INFO/scripts/tackle", line 52, in __generate_final_argument_dict
    argument_dict = self.__merge_two_dicts(argument_dict, component.update_arguments())
  File "/usr/local/lib/python2.7/dist-packages/tacklebox-0.0.1-py2.7.egg/tacklebox/components/rendering_component.py", line 25, in update_arguments
    return self.get_docker_argument_dict()
  File "/usr/local/lib/python2.7/dist-packages/tacklebox-0.0.1-py2.7.egg/tacklebox/components/rendering_component.py", line 42, in get_docker_argument_dict
    volume_dict.update(self.extract_required_commands())
  File "/usr/local/lib/python2.7/dist-packages/tacklebox-0.0.1-py2.7.egg/tacklebox/components/base_component.py", line 58, in extract_required_commands
    commands = [which(command)[0] for command in self.required_commands]
IndexError: list index out of range
```

**Comment by jon-weisz** [comment]
Hello @porst17 ! Thanks for your feedback. I forgot to update the readme after refactoring to make the setup.py install command work. The tackle command is now installed, as you noticed. 

I will investigate your issue later today. My best guess from a glance at the error output is that your system doesn't have the mesa-utils package. We use the glxinfo binary from that package to figure out which libraries to link in to the container, and the glxgears binary to demonstrate them. 

In the longer term, this project is likely to be discontinued, as I am currently merging it's capabilities with docker-hica project (https://github.com/shaded-enmity/docker-hica). This is a similar project, and so rather than duplicate effort we are merging the two. 

For now, if you need these capabilities, keep using tacklebox (if I can get it to work for you), because docker-hica library injection isn't ready yet.

**Comment by porst17** [comment]
I installed `mesa-utils` and got one step further. The above error message disappeared and it seems like it's starting some container. However, on my machine, tacklebox is using the wrong X server. But this is a different issue (#6).

Maybe you should add a list of non-python dependencies to the readme. The dependency on docker seems obvious, but mesa-utils isn't (although I could have guessed it from http://jonweisz.com/docker-hackday-tacklebox). Maybe there are other dependencies as well which are just installed by chance.

**Comment by porst17** [comment]
I will look into `docker-hica` ASAP (unfortunately, not before next Tuesday). It is very likely that I/my team will make use of `tacklebox` or `docker-hica` in one of our projects. I hope, we can contribute something except for bug reports.

**Comment by jon-weisz** [comment]
@porst17 Does https://github.com/Robobench/tacklebox/commit/f699645d3e11a37745ad0f7f438a953b0b795a45 address your concerns here?

**Comment by porst17** [comment]
This should do it. Thanks a lot.
